// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_test.proto

package ru.hh.jclient.common.model;

@SuppressWarnings("unused")
public final class ProtobufTest {
  private ProtobufTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ProtobufTestMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use ProtobufTestMessage.newBuilder() to construct.
    private ProtobufTestMessage() {
      initFields();
    }
    private ProtobufTestMessage(boolean noInit) {}
    
    private static final ProtobufTestMessage defaultInstance;
    public static ProtobufTestMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProtobufTestMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.hh.jclient.common.model.ProtobufTest.internal_static_ProtobufTestMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.hh.jclient.common.model.ProtobufTest.internal_static_ProtobufTestMessage_fieldAccessorTable;
    }
    
    // repeated int32 ids = 1;
    public static final int IDS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> ids_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getIdsList() {
      return ids_;
    }
    public int getIdsCount() { return ids_.size(); }
    public int getIds(int index) {
      return ids_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int element : getIdsList()) {
        output.writeInt32(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int element : getIdsList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getIdsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage result;
      
      // Construct using ru.hh.jclient.common.ProtobufTest.ProtobufTestMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage();
        return builder;
      }
      
      protected ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage.getDescriptor();
      }
      
      public ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage getDefaultInstanceForType() {
        return ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.ids_ != java.util.Collections.EMPTY_LIST) {
          result.ids_ =
            java.util.Collections.unmodifiableList(result.ids_);
        }
        ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage) {
          return mergeFrom((ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage other) {
        if (other == ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage.getDefaultInstance()) return this;
        if (!other.ids_.isEmpty()) {
          if (result.ids_.isEmpty()) {
            result.ids_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.ids_.addAll(other.ids_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              addIds(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addIds(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // repeated int32 ids = 1;
      public java.util.List<java.lang.Integer> getIdsList() {
        return java.util.Collections.unmodifiableList(result.ids_);
      }
      public int getIdsCount() {
        return result.getIdsCount();
      }
      public int getIds(int index) {
        return result.getIds(index);
      }
      public Builder setIds(int index, int value) {
        result.ids_.set(index, value);
        return this;
      }
      public Builder addIds(int value) {
        if (result.ids_.isEmpty()) {
          result.ids_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.ids_.add(value);
        return this;
      }
      public Builder addAllIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.ids_.isEmpty()) {
          result.ids_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.ids_);
        return this;
      }
      public Builder clearIds() {
        result.ids_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ProtobufTestMessage)
    }
    
    static {
      defaultInstance = new ProtobufTestMessage(true);
      ru.hh.jclient.common.model.ProtobufTest.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtobufTestMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtobufTestMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtobufTestMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023protobuf_test.proto\"\"\n\023ProtobufTestMes" +
      "sage\022\013\n\003ids\030\001 \003(\005B\034\n\032ru.hh.jlogic.exampl" +
      "e.model"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ProtobufTestMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ProtobufTestMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtobufTestMessage_descriptor,
              new java.lang.String[] { "Ids", },
              ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage.class,
              ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
