// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf_test.proto

package ru.hh.jclient.common.model;

public final class ProtobufTest {
  private ProtobufTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ProtobufTestMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated int32 ids = 1;
    java.util.List<java.lang.Integer> getIdsList();
    int getIdsCount();
    int getIds(int index);
  }
  public static final class ProtobufTestMessage extends
      com.google.protobuf.GeneratedMessage
      implements ProtobufTestMessageOrBuilder {
    // Use ProtobufTestMessage.newBuilder() to construct.
    private ProtobufTestMessage(Builder builder) {
      super(builder);
    }
    private ProtobufTestMessage(boolean noInit) {}
    
    private static final ProtobufTestMessage defaultInstance;
    public static ProtobufTestMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProtobufTestMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.hh.jclient.common.model.ProtobufTest.internal_static_ProtobufTestMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.hh.jclient.common.model.ProtobufTest.internal_static_ProtobufTestMessage_fieldAccessorTable;
    }
    
    // repeated int32 ids = 1;
    public static final int IDS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> ids_;
    public java.util.List<java.lang.Integer>
        getIdsList() {
      return ids_;
    }
    public int getIdsCount() {
      return ids_.size();
    }
    public int getIds(int index) {
      return ids_.get(index);
    }
    
    private void initFields() {
      ids_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < ids_.size(); i++) {
        output.writeInt32(1, ids_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < ids_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(ids_.get(i));
        }
        size += dataSize;
        size += 1 * getIdsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.hh.jclient.common.model.ProtobufTest.internal_static_ProtobufTestMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.hh.jclient.common.model.ProtobufTest.internal_static_ProtobufTestMessage_fieldAccessorTable;
      }
      
      // Construct using ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        ids_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage.getDescriptor();
      }
      
      public ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage getDefaultInstanceForType() {
        return ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage.getDefaultInstance();
      }
      
      public ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage build() {
        ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage buildPartial() {
        ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage result = new ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          ids_ = java.util.Collections.unmodifiableList(ids_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ids_ = ids_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage) {
          return mergeFrom((ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage other) {
        if (other == ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage.getDefaultInstance()) return this;
        if (!other.ids_.isEmpty()) {
          if (ids_.isEmpty()) {
            ids_ = other.ids_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdsIsMutable();
            ids_.addAll(other.ids_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              ensureIdsIsMutable();
              ids_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addIds(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated int32 ids = 1;
      private java.util.List<java.lang.Integer> ids_ = java.util.Collections.emptyList();;
      private void ensureIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          ids_ = new java.util.ArrayList<java.lang.Integer>(ids_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<java.lang.Integer>
          getIdsList() {
        return java.util.Collections.unmodifiableList(ids_);
      }
      public int getIdsCount() {
        return ids_.size();
      }
      public int getIds(int index) {
        return ids_.get(index);
      }
      public Builder setIds(
          int index, int value) {
        ensureIdsIsMutable();
        ids_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addIds(int value) {
        ensureIdsIsMutable();
        ids_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIdsIsMutable();
        super.addAll(values, ids_);
        onChanged();
        return this;
      }
      public Builder clearIds() {
        ids_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ProtobufTestMessage)
    }
    
    static {
      defaultInstance = new ProtobufTestMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ProtobufTestMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtobufTestMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProtobufTestMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023protobuf_test.proto\"\"\n\023ProtobufTestMes" +
      "sage\022\013\n\003ids\030\001 \003(\005B\034\n\032ru.hh.jclient.commo" +
      "n.model"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ProtobufTestMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ProtobufTestMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ProtobufTestMessage_descriptor,
              new java.lang.String[] { "Ids", },
              ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage.class,
              ru.hh.jclient.common.model.ProtobufTest.ProtobufTestMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
